### PR TITLE
Add the ProcessControlFlowGuardPolicy mitigation policy

### PR DESCRIPTION
**Pull request by fllombard**
Add the ProcessControlFlowGuardPolicy mitigation policy.

### CODE REVIEW

**Comment by fllombard** [comment]
I just signed the CLA.

**Comment by fllombard** [comment]
I just updated my google account to add both email addresses and sign the CLA.

**Comment by tyranid** [comment]
It still seems to think you've not correctly signed the CLA. Perhaps you need to redo the commit?

**Comment by fllombard** [comment]
The email address was incorrect. Sorry it is my first pull request...

**Pull request closed without merging**
